version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend.dockerfile
    depends_on:
      - db
      - redis
    environment:
    - REQUEST_ORIGIN=http://localhost:5001 
    - REDIS_HOST=redis
    - POSTGRES_HOST=db
    ports:
    - 8080:8080
    restart: unless-stopped
  frontend:
    build:
      context: .
      dockerfile: frontend.dockerfile
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080
    ports:
      - 5001:5000
  redis:
    image: redis
  db:
    image: postgres
    environment:
    - POSTGRES_PASSWORD=postgres
    volumes:
     - ./database:/var/lib/postgresql/data
  nginx:
    image: nginx
    depends_on:
      - frontend
      - backend
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
