# Note for examiner: frontend is running on :5001

version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend.dockerfile
    environment:
    - REQUEST_ORIGIN=http://localhost:5001 
    ports:
    - 8080:8080
  frontend:
    build:
      context: .
      dockerfile: frontend.dockerfile
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080
    ports:
      - 5001:5000
